services:
  - type: web
    name: rag-chat-assistant
    env: python  # 强制指定 Python 环境
    buildCommand: |
      pip3 install --upgrade pip
      pip3 install -r requirements.txt
      python download_data.py
    startCommand: |
      streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"